name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      context:
        type: string
        default: .
      dockerfile:
        type: string
        default: Dockerfile
      image_tag:
        type: string
        required: true
      image_tag_latest:
        type: string
        required: true
      push-image:
        type: boolean
        default: true
      repository:
        type: string
        required: true
    secrets:
      cash-registry:
        required: true
      github-token:
        required: true
      registry:
        required: true

jobs:
  build-and-push:
    name: Build and push docker image
    runs-on: self-hosted-general
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up docker context for buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders
          version: v0.9.1
      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.registry }}
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          build-args: |
            GITHUB_TOKEN=${{ secrets.github-token }}
          cache-from: type=registry,ref=${{ secrets.cash-registry }}/${{ inputs.repository }}:buildcache
          cache-to: type=registry,ref=${{ secrets.cash-registry }}/${{ inputs.repository }}:buildcache,mode=max
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: ${{ inputs.push-image }}
          tags: |
            ${{ secrets.registry }}/${{ inputs.repository }}:${{ inputs.image_tag }}
            ${{ secrets.registry }}/${{ inputs.repository }}:${{ inputs.image_tag_latest }}
