name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      CONTEXT:
        type: string
        default: .
      CACHE_REGISTRY:
        type: string
        default: cache-registry.mrcr.io
      REGISTRY:
        type: string
        default: 155215722524.dkr.ecr.eu-central-1.amazonaws.com
      DOCKERFILE:
        type: string
        default: Dockerfile
      IMAGE_TAG:
        type: string
        default: ${{ github.ref_name }}-${{ github.run_number }}
      IMAGE_TAG_LATEST:
        type: string
        default: ${{ github.ref_name }}-latest
      NO_CACHE:
        type: boolean
        default: false
      PUSH_IMAGE:
        type: boolean
        default: true
      REPOSITORY:
        type: string
        default: ${{ github.event.repository.name }}
      RUNNERS:
        type: string
        default: self-hosted-general
    secrets:
      ACCESS_TOKEN:
        required: true
      BUILD_ARGS:
        required: false
      SLACK_BOT_TOKEN:
        required: false

jobs:
  get-runners-list:
    name: Get runners list output
    runs-on: ubuntu-22.04
    steps:
      - name: Create runners list output
        id: runners-list
        run: |
          import os

          runners = str("${{ inputs.RUNNERS }}".split(","))
          os.system(f'echo "matrix={runners}" >> $GITHUB_OUTPUT')
        shell: python
    outputs:
      matrix: ${{ steps.runners-list.outputs.matrix }}

  build-and-push-images:
    name: Build and push docker image
    needs: get-runners-list
    strategy:
      fail-fast: true
      matrix:
        runner: ${{ fromJson(needs.get-runners-list.outputs.matrix) }}
    runs-on: ${{ matrix.runner }}
    outputs:
      image_tag: ${{ steps.image-tags.outputs.image_tag }}
      image_tag_amd64: ${{ steps.image-tags.outputs.image_tag_amd64 }}
      image_tag_arm64: ${{ steps.image-tags.outputs.image_tag_arm64 }}
      image_tag_latest: ${{ steps.image-tags.outputs.image_tag_latest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up docker context for buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders
          version: v0.9.1
      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.REGISTRY }}
      - name: Customize image list
        id: image-list
        run: |
          import os

          RUN_NUMBER = "${{ github.run_number }}"
          TAG, TAG_LATEST = "${{ inputs.IMAGE_TAG }}", "${{ inputs.IMAGE_TAG_LATEST }}"
          REGISTRY, REPOSITORY = "${{ inputs.REGISTRY }}", "${{ inputs.REPOSITORY }}"

          def create_image_tag(tag: str, is_tag_latest: bool = False) -> str:
              repository = f"{REGISTRY}/{REPOSITORY}"
              if '/' not in tag:
                  return f"{repository}:{tag}"
              else:
                  return f"{repository}:{'build-latest'}" if is_tag_latest else f"{repository}:{f'build-{RUN_NUMBER}'}"

          output_tag = create_image_tag(TAG)
          output_tag_latest = create_image_tag(TAG_LATEST, True)

          os.system(f'echo "IMAGE_TAG={output_tag}" >> $GITHUB_OUTPUT')
          os.system(f'echo "IMAGE_TAG_LATEST={output_tag_latest}" >> $GITHUB_OUTPUT')
        shell: python
      - name: Build and push docker image
        id: docker-build
        uses: docker/build-push-action@v3
        with:
          build-args: |
            GITHUB_TOKEN=${{ secrets.ACCESS_TOKEN }}
            ${{ secrets.BUILD_ARGS }}
          cache-from: type=registry,ref=${{ inputs.CACHE_REGISTRY }}/${{ inputs.REPOSITORY }}:buildcache-${{ runner.arch }}
          cache-to: type=registry,ref=${{ inputs.CACHE_REGISTRY }}/${{ inputs.REPOSITORY }}:buildcache-${{ runner.arch }},mode=max
          context: ${{ inputs.CONTEXT }}
          file: ${{ inputs.DOCKERFILE }}
          no-cache: ${{ inputs.NO_CACHE }}
          push: ${{ inputs.PUSH_IMAGE }}
          tags: |
            ${{ steps.image-list.outputs.IMAGE_TAG }}-${{ runner.arch }}
      - name: Prepare image tags output
        id: image-tags
        if: ${{ inputs.PUSH_IMAGE }}
        run: |
          import os

          runner_arch = "${{ runner.arch }}"
          image_tag = "${{ steps.image-list.outputs.IMAGE_TAG }}"
          image_tag_latest = "${{ steps.image-list.outputs.IMAGE_TAG_LATEST }}"

          os.system(f'echo "image_tag={image_tag}" >> $GITHUB_OUTPUT')
          os.system(f'echo "image_tag_latest={image_tag_latest}" >> $GITHUB_OUTPUT')

          if runner_arch == "ARM64":
              os.system(f'echo "image_tag_arm64={image_tag}-{runner_arch}" >> $GITHUB_OUTPUT')
          elif runner_arch == "X64":
              os.system(f'echo "image_tag_amd64={image_tag}-{runner_arch}" >> $GITHUB_OUTPUT')
        shell: python

  build-and-push-manifest:
    name: Build and push docker manifest
    needs: build-and-push-images
    runs-on: self-hosted-general
    if: ${{ inputs.PUSH_IMAGE }}
    steps:
      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.REGISTRY }}
      - name: Build and push docker manifest
        env:
          IMAGE_TAG_LATEST: ${{ needs.build-and-push-images.outputs.image_tag_latest }}
          IMAGE_TAG_AMD_64: ${{ needs.build-and-push-images.outputs.image_tag_amd64 }}
          IMAGE_TAG_ARM_64: ${{ needs.build-and-push-images.outputs.image_tag_arm64 }}
          IMAGE_TAG: ${{ needs.build-and-push-images.outputs.image_tag }}
        run: |
          docker manifest create $IMAGE_TAG_LATEST $IMAGE_TAG_AMD_64 $IMAGE_TAG_ARM_64
          docker manifest create $IMAGE_TAG $IMAGE_TAG_AMD_64 $IMAGE_TAG_ARM_64
          docker manifest push $IMAGE_TAG_LATEST
          docker manifest push $IMAGE_TAG

      # - name: Slack alert condition
      #   if: success() || failure()
      #   id: slack-alert-flag
      #   run: |
      #     import os

      #     BRANCH_NAME = '${{ github.ref_name }}'
      #     OUTCOME = '${{ steps.docker-build.outcome }}'
      #     PUSH_IMAGE = bool('${{ inputs.PUSH_IMAGE }}')
      #     SLACK_TOKEN = '${{ secrets.SLACK_BOT_TOKEN }}'

      #     general_condition = BRANCH_NAME in ['develop', 'master'] and PUSH_IMAGE and SLACK_TOKEN != ''
      #     success_condition = OUTCOME == 'success' and general_condition
      #     failure_condition = OUTCOME == 'failure' and general_condition

      #     print(success_condition)
      #     print(failure_condition)

      #     os.system(f'echo "SLACK_SUCCESS_FLAG={success_condition}" >> $GITHUB_OUTPUT')
      #     os.system(f'echo "SLACK_FAILURE_FLAG={failure_condition}" >> $GITHUB_OUTPUT')
      #   shell: python
      # - name: Send a successful Slack notification
      #   if: success() && steps.slack-alert-flag.outputs.SLACK_SUCCESS_FLAG == 'True'
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     channel-id: "C049W03GZQT"
      #     payload: |
      #       {
      #         "text": ":white_check_mark: *${{ inputs.REPOSITORY }}* – `${{ github.ref_name }}-${{ github.run_number }}` successful build"
      #       }
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      # - name: Send a failure Slack notification
      #   if: failure() && steps.slack-alert-flag.outputs.SLACK_FAILURE_FLAG == 'True'
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     channel-id: "C049W03GZQT"
      #     payload: |
      #       {
      #         "text": ":ahhhhhhhhh: *${{ inputs.REPOSITORY }}* – `${{ github.ref_name }}-${{ github.run_number }}` failed build:\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      #       }
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
